In [1]:
# Ans no 1:-
import numpy as np

mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[ 1  4  6]
 [ 7  5 88]
 [ 8  5 77]]  and 

[[12 43 74]
 [ 5  8  3]
 [ 8  9  9]]  is 

[[13 47 80]
 [12 13 91]
 [16 14 86]] 


In [2]:
# Ans no  2:-
import numpy as np

mat1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
mat2 = np.array([[2,4,7],
        [55,67,8],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  and 

[[ 2  4  7]
 [55 67  8]
 [ 8  9  1]]  is 

[[2848 3442  491]
 [ 423  517   81]
 [  89  121   73]] 


In [4]:
# Ans no 3:-
def transpose_matrix(matrix):
    rows = len(matrix)
    columns = len(matrix[0])

    #a new matrix with swapped rows and columns
    transposed_matrix = [[0 for _ in range(rows)] for _ in range(columns)]

    for i in range(rows):
        for j in range(columns):
            transposed_matrix[j][i] = matrix[i][j]

    return transposed_matrix


# Example usage
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("Original Matrix:")
for row in matrix:
    print(row)

transposed = transpose_matrix(matrix)

print("Transposed Matrix:")
for row in transposed:
    print(row)

Original Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Transposed Matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [5]:
# Ans no 4:-
Arr = input("Enter string:")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string:python is best
best
is
python


In [7]:
# Ans no 5:-
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display
print(rem_punc)

Enter a string with punctuations'''!()-[]{};:'"\,<>./?@#$%^&*_

